In [116]:
import numpy as np

In [117]:
# Learning rate
a: float = 0.1

In [119]:
w1 = np.random.rand(4, 2)
w1.shape

(4, 2)

In [120]:
def propagate_w1(input_: np.array):
    return np.append(input_ @ w1, 1)

In [122]:
propagate_w1([6, 8, 4, 1]).shape

(3,)

In [123]:
w2 = np.random.rand(3, 10)
w2

array([[0.11151492, 0.24947072, 0.55343262, 0.66870519, 0.70959002,
        0.93905256, 0.31005826, 0.51871081, 0.14156209, 0.13862528],
       [0.32753723, 0.19967571, 0.5885687 , 0.17288607, 0.57180157,
        0.7701458 , 0.59187137, 0.97156444, 0.4294568 , 0.68390733],
       [0.66897383, 0.9220142 , 0.89941051, 0.10770092, 0.41372676,
        0.72063756, 0.65243069, 0.48013163, 0.93580896, 0.44336808]])

In [124]:
def propagate_w2(input_: np.array):
    return input_ @ w2

In [125]:
propagate_w2([9, 4, 1]).shape

(10,)

In [126]:
def propagate(input_: np.array):
    # return propagate_w2(propagate_w1(input_))
    return np.append(input_ @ w1, 1) @ w2

In [127]:
propagate([6, 8, 4, 1]).shape

(10,)

In [50]:
# generar datos de entrenamiento
y = np.random.rand(10)
y

array([0.64101667, 0.84703702, 0.19453029, 0.91877494, 0.75159564,
       0.52585762, 0.99389709, 0.76386408, 0.18673076, 0.67242353])

In [95]:
x = np.append(np.random.rand(3), 1)
x

array([0.99757638, 0.95200476, 0.57012808, 1.        ])

In [140]:
w1.shape

(4, 2)

In [145]:
w2.shape

(3, 10)

In [168]:
def retro_propagate(x: np.array, y: np.array):
    global w1, w2
    o1 = np.append(x @ w1, 1)
    print('o1', o1.shape)
    o2 = o1 @ w2
    d2 = np.multiply(o2, np.multiply(1 - o2, y - o2))
    # output neuron:
    w2 += a * np.outer(o1, d2)
    # hidden neuron:
    wdwdwd = []
    for i in range(w2.shape[0]):
        wd_i = 0
        for j in range(w1.shape[1]):
            wd_i += w1[i, j] * d2[j]
        wdwdwd.append(wd_i)
    print('wdwdwd', np.array(wdwdwd).shape)
    print('1 - o1', (1 - o1).shape)
    print('np.array(wdwdwd)', np.array(wdwdwd))
    
    qwe =  np.multiply(1 - o1, np.array(wdwdwd))
    # print('qwe', qwe.shape)
    # d1 = np.multiply(o1, qwe)
    # print('d1', d1.shape)
    # w1 += a * np.outer(x, d1)

In [169]:
retro_propagate(x, y)

o1 (3,)
wdwdwd (3,)
1 - o1 (3,)
np.array(wdwdwd) [inf inf inf]


/tmp/ipykernel_998163/3623448229.py:20: RuntimeWarning: invalid value encountered in multiply
  qwe =  np.multiply(1 - o1, np.array(wdwdwd))


In [170]:
!pip install --upgrade gdown

Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: colab 1.13.5 has a non-standard dependency specifier pytz>=2011n. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of colab or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: gpg 1.23.2-unknown has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of gpg or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
  Attempting uninstall: gdown
    Found existing installation: gdown 4.6.0
    Uninstalling gdown-4.6.0:
      Successfully uninstalled gdown-4.6.0


In [171]:
!gdown --id 1x0JbCKDCGtynM6GnunAOdDYlyt7dI0B- -O mnist.txt

/home/dayan3847/.local/lib/python3.10/site-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1x0JbCKDCGtynM6GnunAOdDYlyt7dI0B-
To: /home/dayan3847/PycharmProjects/machine_learning/1_3_multi_layer_perceptron/src/v2/mnist.txt
100%|██████████████████████████████████████| 9.13M/9.13M [00:00<00:00, 9.94MB/s]
