In [1]:
import numpy as np

In [3]:
z = np.zeros(2)
z

array([0., 0.])

In [4]:
z.shape

(2,)

In [10]:
c = np.row_stack(z)
c

array([[0.],
       [0.]])

In [7]:
c.shape

(1, 2)

In [9]:
np.column_stack([np.zeros(2)]).shape

(2, 1)

In [12]:
np.zeros(2)[:, np.newaxis].shape

(2,)

In [14]:
r = np.random.rand(5)[np.newaxis, :]
r

array([[0.27635154, 0.84829676, 0.04781812, 0.67443626, 0.08717817]])

In [16]:
r.shape

(1, 5)

In [20]:
r[0, 0]

0.2763515373384464

In [21]:

import sympy as sp

In [22]:
_X: sp.Symbol = sp.MatrixSymbol('X', 2, 1)
# mu_ mayuscula
_M: sp.MatrixSymbol = sp.MatrixSymbol('mu_', 2, 1)
# sigma mayuscula
_C: sp.MatrixSymbol = sp.MatrixSymbol('sigma', 2, 2)
sp.exp(-.5 * (_X - _M).T * _C.I * (_X - _M))

exp(-0.5*(X.T - mu_.T)*sigma**(-1)*(X - mu_))

In [24]:
a1 = np.array([2, 4])[np.newaxis, :]
a1

array([[2, 4]])

In [25]:
a2 = np.array([3, 5])[:, np.newaxis]
a2

array([[3],
       [5]])

In [27]:
r = a1 @ a2
r

array([[26]])

In [28]:
r[0,0]

26